### ISSUE TITLE
hmm not sure where to share or if its even somen wrong 

### ISSUE THREAD

**Issue by beals1pt0** [jhakonen/wot-teamspeak-mod#22]
File "scripts/client/gui/mods/mod_tessumod.py", line 98, in init
AttributeError: 'module' object has no attribute 'VOIPManager'

2016-08-13 05:17:31.163: NOTICE: [NOTE] (scripts/client/post_processing/__init__.py, 269): The quality = 4 was selected.
2016-08-13 05:17:31.163: NOTICE: [NOTE] (scripts/client/post_processing/__init__.py, 269): The quality = 3 was selected.
2016-08-13 05:17:34.612: NOTICE: [NOTE] (scripts/client/gui/mods/tessumod/ts3.py, 503): TS client query protocol detected
2016-08-13 05:17:34.612: NOTICE: [NOTE] (scripts/client/gui/mods/mod_tessumod.py, 204): Connected to TeamSpeak client
2016-08-13 05:17:34.971: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: LOGIN - 12.8760004044
2016-08-13 05:17:34.974: NOTICE: [NOTE] (scripts/client/ConnectionManager.py, 220): User authentication method: token2
2016-08-13 05:17:37.377: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: CONNECTED - 15.281999588
2016-08-13 05:17:38.543: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SHOW GUI - 16.4479999542
2016-08-13 05:17:43.019: NOTICE: [NOTE] (scripts/client/gui/mods/mod_tessumod.py, 254): Connected to TeamSpeak server 'â˜ __ N.A.F.I.G.Gaming__â˜ '
2016-08-13 05:17:50.491: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: QUESTS SYNC - 28.3959999084
2016-08-13 05:17:50.527: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: USS SYNC - 28.4319992065
2016-08-13 05:17:51.575: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SPACE LOADING START - 29.4799995422
2016-08-13 05:17:51.605: NOTICE: [NOTE] (scripts/client/game.py, 426): [SPACE] Loading space: spaces/hangar_premium_v2
2016-08-13 05:17:51.645: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: VEHICLE LOADING START - 29.5499992371
2016-08-13 05:17:53.068: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: VEHICLE LOADING END - 30.9729995728
2016-08-13 05:17:53.087: ERROR: Traceback (most recent call last):
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/messenger/proto/xmpp/gloox_wrapper.py", line 484, in onHandleIq
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/messenger/proto/xmpp/gloox_wrapper.py", line 506, in __handleEvent
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/messenger/proto/xmpp/spa_requesters.py", line 154, in __handleIQ
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/messenger/proto/xmpp/spa_requesters.py", line 115, in __doCallback
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/gui/shared/utils/requesters/RequestsController.py", line 140, in _callbackWrapper
2016-08-13 05:17:53.087: ERROR:   File "scripts/client/gui/shared/view_helpers/UsersInfoHelper.py", line 176, in <lambda>
2016-08-13 05:17:53.088: ERROR:   File "scripts/client/gui/prb_control/invites.py", line 684, in onUserNamesReceived
2016-08-13 05:17:53.088: ERROR:   File "scripts/client/gui/prb_control/invites.py", line 871, in _inviteMaker
2016-08-13 05:17:53.088: ERROR: AttributeError: 'NoneType' object has no attribute 'get'
2016-08-13 05:17:53.354: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SPACE LOADING END - 31.2590007782
2016-08-13 05:17:53.354: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: HANGAR READY - 31.2590007782
2016-08-13 05:17:53.354: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 276): HANGAR LOADING STATE: SUMMARY TOTAL = 18.3830003738
2016-08-13 05:17:53.355: ERROR: Traceback (most recent call last):
2016-08-13 05:17:53.355: ERROR:   File "scripts/client/gui/shared/utils/requesters/RequestsController.py", line 75, in _doRequest
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/gui/shared/view_helpers/UsersInfoController.py", line 122, in _getNicknames
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/messenger/proto/xmpp/spa_requesters.py", line 92, in resolve
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/messenger/proto/xmpp/spa_requesters.py", line 115, in __doCallback
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/gui/shared/utils/requesters/RequestsController.py", line 140, in _callbackWrapper
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/gui/shared/view_helpers/UsersInfoHelper.py", line 176, in <lambda>
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/gui/prb_control/invites.py", line 684, in onUserNamesReceived
2016-08-13 05:17:53.356: ERROR:   File "scripts/client/gui/prb_control/invites.py", line 871, in _inviteMaker
2016-08-13 05:17:53.356: ERROR: AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jhakonen** [comment]
Hi, thanks for the bug report :)

Unfortunately, there's a bit of bad timing here as I have just released (~30 minutes ago) a new version of the mod which should fix this issue, among other things.

You can get it from here:
https://github.com/jhakonen/wot-teamspeak-mod/releases/download/0.6.7/tessumod-0.6.7-bin.zip

Can you retry this with new version?

**Comment by beals1pt0** [comment]
2016-08-13 05:50:54.543: NOTICE: [NOTE] (scripts/client/gui/mods/mod_tessumod.py, 275): Settings loaded from ini file
2016-08-13 05:50:54.543: ERROR: [EXCEPTION] (scripts/client/gui/mods/mod_tessumod.py, 113):
Traceback (most recent call last):
  File "scripts/client/gui/mods/mod_tessumod.py", line 98, in init
AttributeError: 'module' object has no attribute 'VOIPManager'

2016-08-13 05:50:54.604: NOTICE: [NOTE] (scripts/client/post_processing/__init__.py, 269): The quality = 4 was selected.
2016-08-13 05:50:54.604: NOTICE: [NOTE] (scripts/client/post_processing/__init__.py, 269): The quality = 3 was selected.
2016-08-13 05:50:57.948: NOTICE: [NOTE] (scripts/client/gui/mods/tessumod/ts3.py, 503): TS client query protocol detected
2016-08-13 05:50:57.948: NOTICE: [NOTE] (scripts/client/gui/mods/mod_tessumod.py, 204): Connected to TeamSpeak client
2016-08-13 05:50:58.338: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: LOGIN - 12.736000061
2016-08-13 05:50:58.341: NOTICE: [NOTE] (scripts/client/ConnectionManager.py, 220): User authentication method: token2
2016-08-13 05:51:00.751: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: CONNECTED - 15.1490001678
2016-08-13 05:51:01.932: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SHOW GUI - 16.3309993744
2016-08-13 05:51:06.253: NOTICE: [NOTE] (scripts/client/gui/mods/mod_tessumod.py, 254): Connected to TeamSpeak server 'в __ N.A.F.I.G.Gaming__в '
2016-08-13 05:51:14.051: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: QUESTS SYNC - 28.4489994049
2016-08-13 05:51:14.084: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: USS SYNC - 28.482000351
2016-08-13 05:51:15.008: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SPACE LOADING START - 29.4060001373
2016-08-13 05:51:15.037: NOTICE: [NOTE] (scripts/client/game.py, 426): [SPACE] Loading space: spaces/hangar_premium_v2
2016-08-13 05:51:15.080: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: VEHICLE LOADING START - 29.4780006409
2016-08-13 05:51:16.554: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: VEHICLE LOADING END - 30.9519996643
2016-08-13 05:51:16.922: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: SPACE LOADING END - 31.3199996948
2016-08-13 05:51:16.922: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 248): HANGAR LOADING STATE: HANGAR READY - 31.3199996948
2016-08-13 05:51:16.922: NOTICE: [NOTE] (scripts/client/helpers/statistics.py, 276): HANGAR LOADING STATE: SUMMARY TOTAL = 18.5839996338
2016-08-13 05:51:23.400: ERROR: [ERROR] (scripts/client/messenger/proto/xmpp/log_output.py, 52): XMPP_PY::GENERIC. Error has been received on requesting nicknames (ClientError(error=LOCKED),)

**Comment by jhakonen** [comment]
Oops, you're correct.
Should have checked the log before making the new release. Oh well.

That error shouldn't be a major issue though, not anymore. It might cause some erratic behaviour right at battle's start with the green speech indicator not always showing up when it should.

**Comment by beals1pt0** [comment]
ok just sharing love the mod keep up the great work
