### ISSUE TITLE
are you still working on this 

### ISSUE THREAD

**Issue by beals1pt0** [jhakonen/wot-teamspeak-mod#27]
there was a patch for wot 

Traceback (most recent call last):
2016-12-14 20:15:19.424: INFO:   File "scripts/client/gui/mods/mod_tessumod.py", line 22, in <module>
2016-12-14 20:15:19.424: INFO:   File "scripts/client/gui/mods/tessumod/utils.py", line 21, in <module>
2016-12-14 20:15:19.424: INFO: ImportError: cannot import name g_sessionProvider

**Comment by beals1pt0** [comment]
2016-12-15 22:13:11.106: ERROR: [EXCEPTION] (scripts/client/game.py, 191):
Traceback (most recent call last):
  File "scripts/client/game.py", line 159, in init
  File "scripts/client/gui/shared/personality.py", line 336, in init
  File "<string>", line 281, in init
  File "scripts/client_common/shared_utils/__init__.py", line 49, in forEach
  File "<string>", line 281, in <lambda>
  File "<string>", line 295, in _callModMethod
  File "scripts/client/gui/mods/mod_tessumod.py", line 113, in init
NameError: global name 'LOG_CURRENT_EXCEPTION' is not defined

**Comment by jhakonen** [comment]
Hi beals1pt0,

Thank you, I'm working on this, but unfortunately that isn't the only place where the mod has broken down. 
I'll try to get fixed release out this evening.
